CREATE TABLE user_chat (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ID_user INTEGER,
  ID_chat INTEGER,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_user) REFERENCES users(id),
  FOREIGN KEY (ID_chat) REFERENCES chat(ID)
);