CREATE TABLE event_chat (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ID_event INTEGER,
  ID_chat INTEGER,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_event) REFERENCES events(ID),
  FOREIGN KEY (ID_chat) REFERENCES chat(ID)
);