INSERT INTO genre (genre_name) VALUES ('Hombre');
INSERT INTO genre (genre_name) VALUES ('Mujer');
INSERT INTO genre (genre_name) VALUES ('Agénero');
INSERT INTO genre (genre_name) VALUES ('Andrógine');
INSERT INTO genre (genre_name) VALUES ('Andróginx');
INSERT INTO genre (genre_name) VALUES ('Bigénero');
INSERT INTO genre (genre_name) VALUES ('Cis');
INSERT INTO genre (genre_name) VALUES ('Dos espíritus');
INSERT INTO genre (genre_name) VALUES ('Enby');
INSERT INTO genre (genre_name) VALUES ('F2M');
INSERT INTO genre (genre_name) VALUES ('FTM');
INSERT INTO genre (genre_name) VALUES ('Genderqueer');
INSERT INTO genre (genre_name) VALUES ('Género en cuestionamiento');
INSERT INTO genre (genre_name) VALUES ('Género fluido');
INSERT INTO genre (genre_name) VALUES ('Género neutro');
INSERT INTO genre (genre_name) VALUES ('Género no binario');
INSERT INTO genre (genre_name) VALUES ('Género no conforme');
INSERT INTO genre (genre_name) VALUES ('Género variante');
INSERT INTO genre (genre_name) VALUES ('Hombre a mujer');
INSERT INTO genre (genre_name) VALUES ('Hombre trans');
INSERT INTO genre (genre_name) VALUES ('Hombre trans FtM');
INSERT INTO genre (genre_name) VALUES ('Hombre transexual');
INSERT INTO genre (genre_name) VALUES ('Hombre transexual FtM');
INSERT INTO genre (genre_name) VALUES ('Hombre transgénero');
INSERT INTO genre (genre_name) VALUES ('Hombre transgénero FtM');
INSERT INTO genre (genre_name) VALUES ('M2F');
INSERT INTO genre (genre_name) VALUES ('MTF');
INSERT INTO genre (genre_name) VALUES ('Mujer a hombre');
INSERT INTO genre (genre_name) VALUES ('Mujer trans');
INSERT INTO genre (genre_name) VALUES ('Mujer trans MtF');
INSERT INTO genre (genre_name) VALUES ('Mujer transexual');
INSERT INTO genre (genre_name) VALUES ('Mujer transexual MtF');
INSERT INTO genre (genre_name) VALUES ('Mujer transgénero');
INSERT INTO genre (genre_name) VALUES ('Mujer transgénero MtF');
INSERT INTO genre (genre_name) VALUES ('Neutro');
INSERT INTO genre (genre_name) VALUES ('Ninguno');
INSERT INTO genre (genre_name) VALUES ('Otro género');
INSERT INTO genre (genre_name) VALUES ('Pangénero');
INSERT INTO genre (genre_name) VALUES ('Persona trans');
INSERT INTO genre (genre_name) VALUES ('Persona transexual');
INSERT INTO genre (genre_name) VALUES ('Persona transgénero');
INSERT INTO genre (genre_name) VALUES ('Poligénero');
INSERT INTO genre (genre_name) VALUES ('Trans');
INSERT INTO genre (genre_name) VALUES ('Transexual');
INSERT INTO genre (genre_name) VALUES ('Transexual femenina');
INSERT INTO genre (genre_name) VALUES ('Transexual masculino');
INSERT INTO genre (genre_name) VALUES ('Transfemenina');
INSERT INTO genre (genre_name) VALUES ('Transgénero');
INSERT INTO genre (genre_name) VALUES ('Transgénero femenina');
INSERT INTO genre (genre_name) VALUES ('Transgénero masculino');
INSERT INTO genre (genre_name) VALUES ('Transmasculino');
